from time import sleep
from userbot import CMD_HELP
from userbot.events import register


@register(outgoing=True,pattern='^.asw(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**LO MW CARI NAMA MENDING GAUSAH BEGO, NAMA LO AJA KAYAK BULAN BULANAN DIGOLO TOLOL OH IYA BAPAK LO KAN GIGOLO MAKANYA SIFAT ANAKNYA KAYAK LONTE UDAH UDAH LONTE UDAH TUA PUN BODOH LAGI MAKANYA KAU AJARIN BAPAK SAMA MAMAK KAU NGEWE BIAR GAK SALAH CETAK DIA BIAR GAK KAYAK KAU HASIL SPERMANYA LAHIRNYA DIBECEKAN SIH IYA DIBECEKAN DEKAT SEMAK SEMAK LALANG YG JADI RUMAH KALIAN SEKARANG DUH MISKIN BANGET SIH HIDUP LO INILAH AKIBAT BAPAK LO YG MOKONDO MODAL KONTOL DOANG SALAH PUNYA BAPAK SIH MAKANYA KALAU MAMAKNYA MW NIKAH DIPILIHIN DONG BAPAKNYA KAN MAMAMU MASIH PERAWAN GAPERNAH NGELAHIRIN KAU KAN DIBELI DI KEBUN BINATANG.**") 
    sleep(6)
    await typew.edit("**DAN KELUARGA MU KAN BINATANG SEMUA BEGO TOLOL BANGSAD MENDING LO TURUN AJA BEGO DARIPADA RUSAK MENTAL LO DISINI KASIHAN BAPAK MAMAK KAU UDAH GILA MAKIN GILA MEREKA NENGOK KAU GILA EH TAPI KALAU MAU GILA GPP SIH GILA AJA GK ADA YG LARANG KOK LAGIAN SEKOLAH NYA SLB SIH LULUSAN ANAK ANAK DAJAL YG MENJADI TOLOL BODOH DAN GILA HADEH IDIOT BANGET SIH NASIB LO   MENDING LO MATI AJA DAH GANTUNG DIRI NOH DIJEMURAN BH SEKALIAN PAKE JEPITAN KOLOR SUPAYA NAMPAK HINA DAN NAJIS JANGAN LUPA SEBELUM BUNUH DIRI NGEWE DULU SAMA ANJINGKU YAH SIAPA TAU DAPAT HIDAYAH KAU DARI ANJING KU KAN DAN GK JADI BUNUH DIRI BIAR ADA JUGA KELUARGA MU DIJALANAN KASIHAN GW SAMA LOE DIJALAN GAK ADA KELUARGA**") 
    sleep(14)
    await typew.edit("**APAASIN NGEBACOT MULU LO ITU GAK PUNYA KOSAKATA LAHIR AJA GAK PAKE MULUT GAK USAH PINJAM PINJAM MULUT ORANG DEH YAH KALI ADA YG MW MINJEMIN INI KAGAK ADA HAHAHA MENDINGAN LO NGEMIS DIJALANAN SONO KUMPULIN DUIT DAN SAMPAH BIAR ADA BIAYA OPERASI UNTUK BIKIN MULUT BIAR LO ITU BISA NGENYEPONG ,NGEBACOT DAN MENJADI JAMET KASIHAN GW LIAT BENTUKKAN MUKA LO GAK ADA BENTUKNYA LAHIR NYA SALAH LOBANG SIH MAKANYA BENTUKKANNYA KAYA GINI HAHA DASAR TOLOL.**")


@register(outgoing=True, pattern='^.tua(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**EH BOCAH TUA HINA, KALO TUANYA TUA AJA GOBLOK GA COCOK BOCAH TUA KAYA LU MAIN KEK GINIAN TOLOL UDAH BAU TANAH JADINYA GAUSAH BELAGU KONTOL.**")
    sleep(7)
    await typew.edit("**URUSIN AJA BEGO KUBURAN LU ITU BESOK CALON RUMAH LU SEKALI SEKALI YEKAN LU TINGGAL DIRUMAH GA DI RONGSOKAN MULU**")
   

@register(outgoing=True, pattern='^.stress(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**NI YE GUA KASIH TAU SAMA LU YA BEGO LU BAKAL PUNYA ANAK CUCU LU KASIH TAU AJA KETURUNAN LU TUH KALO UDAH HINA YA HINA BEGO.**")
    sleep(6)
    await typew.edit("**GUA SARANIN JUGA LU SURUH ANAK LU NYEKOLAHIN CUCU LU BESOK BIAR PINTER GA KEK LU DONGO GOBLOK IDIOT YEKAN.ANAK LU SURUH KERJA BIAR PUNYA DUIT BIAR BISA MAKAN JANGAN BERGANTUNG SAMA BANSOS MULU.NIH YA KALO KOSA KATA MASIH NYURI DARI ORANG LAINAPA LAGI COPY PASTE GAUSAH BELAGU KONTOL.MAKANYA OTAKNYA DIPAKE TOLOL JANGAN DITARO DI DENGKUL MULU.**")
    sleep(14)
    await typew.edit("**KEBANYAKAN COLI SIH MAKANYA JADI KOPONG TUH DENGKUL ISI OTAK LU AJA CUMA DEBU SAMA SARANG LABA LABA BEGO**")
    sleep(6)
    await typew.edit("**GA USAH SO MANTEP BEGO KALO LEHER MASIH BEDAKI SELANGKANGAN BEJAMUR KONTOL NANAHAN MAKANYA KALO MANDI PAKE AIR BUKAN PAKE PASIR.**")
    sleep(6)
    await typew.edit("**GUA JAGO GA KAYA LU YG SOSOAN JADI JAGOAN KOSA KATA CUMA 1-10 TERUS DIBALIKIN 10-1 SAMA KAYA HIDUP LU MUNDAR MANDIR SANA SINI CARI PINJEMAN BUAT MAKAN SEHARI HARI YEKAN**")
    sleep(7)
    await typew.edit("**MAU SAMPE KAPAN PUN GUA BAKALAN LADENIN LU GOBLOK, LADENIN MANUSIA PURBA JELEK KEK LU GABAKALAN BERENTI GUA TOLOL NI YE GUA SARANIN MENDING LU APUS TELE DAH KONTOL.**")


@register(outgoing=True, pattern='^.gajelas(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**YA AMPUN LU NGOMONG APA? GA NYAMBUNG KONTOL KAYA KEHIDUPAN LU MAKANYA ORG ORG KAYA LU GABAKALN MAJU HIDUPNYA APA LAGI ORG ORG BAWAHAN KAYA LU.**")


@register(outgoing=True, pattern='^.kismin(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**GUA KASIH TAU NI AMA LO MENDING PIKIRIN BEROBAT MAU GMNA LO MAKAN AJA SUSAH HARI HARI IDUP LO SUSAH MULU NGEMIS GA DIKASIH EMAK LO NGELONTE GA LAKU GEGARA MEMEKNYA SUMBING PANUAN KURAPAN BECEK KEK APAAN TAU BOKAP LO KAN UDH CACAT ADEK LO JUAL TISU GA LAKU LAKU MENDING NIH YA GUA KASIH TAU LO ITU MENDING BIKIN BPJS KE PEMERINTAH EH PERCUMA SI PEMERINTAH JUGA MALES NGURUSIN BPJS ORANG MISKIN GEMBEL HINA KAYA LO SECARA LO ITU GA GUNA LAGI DI DUNIA MENDING ITU LO MATI ABIS ITUU GUA SURUH ADE LO KASIH TAU DIMANA KUBURAN LO NANTI NIH YA GUA KENCINGIN KUBURAN LO ABIS ITU GUA GAMBAR BATU NISAN LO PAKE PILOK GAMBAR KONTOL YANG GEDE AMA GRAVITY TULISAN DIA ATHEIS GAUSAH DIKASIH PAPAN NISAN KONTOL.**")


@register(outgoing=True, pattern='^.smph(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**GAUSAH BEGITU LU KEREN LU BEGITU? GA TOLOL MENDING LU MENYENDIRI DIRUMAH DAN LU SIAPIN TISU BEKAS LU LAP IN KE MULUT LU BUAT LU LAP IN KE KONTOL LU YG ABIS COLI BEGO LU MENDING AMBIL BAJU KELUAR DARI RUMAH BIAR GAK NOLEP KASIHAN BEGO HIDUP LU YANG MIRIS TANPA DI ASUH OLEH ORANG TUA ELU KARNA GAK KUAT NGURUS ELU YANG DIKIT DIKIT JADI ANAK GAK GUNA EMAK LU TUH SEBENERNYA GAK TEGA LIAT MUKA ELU YANG KASIHAN MAKANYA DIA PENGEN NGURUS ELU WALAU KADANG MUAK ANGGEP INI ANAK MANUSIA ATAU ANAK BINATANG ATAU JUGA SPESIES HAMA AHAHAA NYADAR TOLOL LU DARI TADI OMONGIN DIRI LU SENDIRI YG HIDUP NYA GAPERNAH ENAK HIDUP LU SELALU DI PENUHI PENDERITAAN GAADA YG KASIAN AMA NASIB LU YG BEGITU ADANYA ORANG MALAH JIJIM NGELIAT LU GITU NASIB LU AJA UDAH HINA APALAGI MUKA LU LEBIH HINA MAKANYA ORANG GAADA YG MAU BANTUIN KARNA ORANG GAMAU NGELIAT MUKA LU YG MENJIJIKAN ITU ORANG ORANG MAU MUNTAH NGELIAT LU TOLOL**")


@register(outgoing=True, pattern='^.nyg(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**ELU TUH JANGAN SO KAYA TOLOL ELU KEK GITU BIAR DI BILANG APA PANSOS LU DI SINI GOBLOK GOBLOK YANG ADA ELU KESINI DI HINA KARNA TEMEN ELU YANG TOLOL SEGALA NYENGOL NYENGOL ALIANSI GUA BIAR APA ELU MAU PANSOS KARNA DI SINI BANYAK CEWE GUA TAU ELU DI GRUP TUH NYARI CEWE KARNA ELU DI DUNIA NYATA GADA YANG MAU KARNA MUKA ELU TUH BURUK RUPA HINA SINI DAH MUKA ELU YANG HINA BIAR TAU GIMANA MUKA ELU YANG HINA GUA LUDAHIN**")


@register(outgoing=True, pattern='^.lah(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**ORANG TUA LO DAPET DUIT SUSAH GA BAKAL PERCAYA GUA DIA DAPET DUIT HALAL KE HARAM KE, GAPERCAYA SAMA ORANG MISKIN KAYA LO YA BURUK TYPO LO BIKIN GUA ENEGGG, RUMAH MASI TENDA AJA BELAGU TOLOL WKWKWK GOBLOK MANGKANYA TANYAIN EMA ELU YANG JADI BABU DIRUMAH ELU JANGAN BISA NYA NGANDELIN EMA ELU MULU JADI BABU DIRUMAH GUA SUKA KASIAN RUMAH GUA KAN GEDE YA EMA ELU KAN UDH TUA PEOT BAU TANAH BENTAR LAGI JUGA MATI. NIH GUA BILANGIN YA KALO WAR TYPING BALESS KOSA KATA LAWAN GUE TOLOL JANGANN MALAH BILANG SOK TAUU ITU TANDA NYA LU KALAHH TOLOLL AHAHAHA GOBLOK**")


@register(outgoing=True, pattern='^.cwe(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**Buat cewe gausa so soan ngeghosting mane muka lu kaya puting Item dekil, kalau bening ya masih mending gw saranin nih ye kalau akal kecil masih kaya kelingking mending gausa deh, mending lu pergi mancing**")


@register(outgoing=True, pattern='^.gs(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**JANGAN CARI GUE KALO MUKA LO UDH KE BOCAH NGERO TAU GAK OH IYA LO KAN GAK TAU KARNA LO ITU HANYA BAWAHAN DOANG KARNA LO ITU BOCAH BOCAH MISKIN HARTA MISKIN KOSA KATA MAKANYA LO ITU HANYA SAMPAHAN SAMPAHAN BOTOL BOTOL MALAH KAYA JADI TUKANG MULUNG KESIAN KAN LO BOCAH BOCAH MULUNG YANG DI GAJI CUMAN 1 SERIBUAN DOANG CIH MAKANYA LO ITU DI KASIHANIN SAMA ORANG MAKANYA LO DI INJEK INJEK MUKA LO UDH ADA TANDA SENDAL DI MUKALU MEREK SWALOW KESIAN BET KSEIAN HADEH MUKA SENDAL SWALOW DI TARIK PUTUS KAYA PALALO DI TARIK PUTUS KAYA KUYANG ABIS ITU PALALI DI TENDANG TUH YANG UDH JADI KUYANG KE BOLA API DI MAENIN MAKANYA LO ITU BADANYA KAN MISAH PALA SAMA BADA JADI KUYANG BADAN LO DI ENTOT BOKAP LO YANG NAMANYA DAJAL KAN EMAK BAPAK LO PERSILANGAN DAJAL SAMA EMAK LO ITU YANG MEMEKNYA UDH LOBEH BET LOBEH TUH KARNA DI MASUKIN KONTOL DAJAL YANG GEDENYA KAYA TOWER SINYAL GOBLOK KAN RUMAH LUU DI PLOSOK NOH YANG PENUH DENGAN BABI HUTAN MAKANYA LO SERING DI SRUDUKIN AAMA BABI HUTAN KAN TUH PALALO YANG AKHIRNYA PALALO BENTUK TRAPESIUM APAH SEGITA SAMA KAKI YANG LUMPUH ELUH YANG GARA GARA KESERET SAMA MOBIL KIJANG NIATNYA NEBENG EH MALAH DI GAS AKHIRNYA LO PEGANGAN TUH SAMA BAK BELAKANG MOBILNYA AKHIRNYA KAKI LO TUH KESERET DENGAN TULANG LO YANG KELIATAN DAH DI AMPUTASI KAKI LO ITU MENJADI MINTA MINTA DI PINGGIT JALANAN ITU HADEH BOCAH BOCAH MINTA MALAH DI LEMPARIN SAMPAH YANG ISINYA PEMPES BAYI MUKALO JADI JELEK BENER AKHLAK LO KYK BABI**")


@register(outgoing=True, pattern='^.jele(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**BERAPA KALI SI GUA BILANG GUA GA BAKAL IRI SAMA ORANG JELEK YANG BENTUKANYA KAYA UNDUR UNDUR**")


@register(outgoing=True, pattern='^.cih(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**MUKA BAPAK LU KEK KELAPA SAWIT ANJING, GA USAH NGATAIN ORANG, MUKA LU AJA KEK GEMBEL TEXAS GOBLOK!!**")


@register(outgoing=True, pattern='^.tw(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**HEH BOCAH TUA NGAPAIN LO DISINI TOLOL BUKANNYA KERJA GITU APA NGGA NGEMIS KEK BIAR DAPET DUIT BUAT MAKAN. MAKANYA NI YE ANAK IDIOT KLO PUNYA ORANG TUA ITU BILANGIN PAK KERJA PAK JANGAN KERJAANNYA MANCING MLU BIAR APA COBA KAYA GTU PENGANGGURAN BANGET AJG, BAPA LU NYUSAHIN ORANGNYA GA SEKALIAN AJA LU BUNUH BIAR GA RIBET GITU, LU APAIN KE CEKEK KLO GA LU RACUNIN PAKE RACUN KECOA BIAR BERKURANG TUH BENALU DUNIA KAYA BAPA LU, HIDUP NYA KEBANYAKAN NGEHALU MLU NGEDOA MAH NGEDOA MUDAH MUDAHAN HIDUP GUA ENAK, TAPI USAHA GAK ADA TOLOL, DIMANA MANA KLO MAU SUKSES USAHA GBLK BUKAN DARI SEKEDAR OMONGAN, TAPI SETIAP OMONGAN YG KELUAR DARI MULUT BAPA LO GAK ADA YG BERGUNA AJG YA SAMA KEK HIDUPNYA YG UNFAEDAH GADA GUNA, EMA LU LAGI BUKANNYA JAGAIN ANAK DIDIK ANAK YG BNER GITU, MALAH KELAKUAN NYA GA BNER SEGALA MEMEK DI BIGSALE, BUJUK RAYU SEGITU SEPI NYA MEMEK EMA LU SAMPE DI OBRAL MURAH BEGITU DONGO, BIARPUN DI BIG SALE IN NIH YEH GUA KASIH TAU SAMA LU GA ADA YG MAU NOEL MEMEK EMA LU YANG BERNANAH KEK GITU, JIJI BEGO JANGAN KAN NOEL LIAT NYA AJA NAJIS, UDH BERLUMUT GTU KEK BATU KALI**")


CMD_HELP.update({
    "nyindir":
    "•CMD: `.asw`\
    \n•penjelasan: sperma haram ga tau diri\
    \n\n•CMD: `.tua`\
    \n•Penjelasan: Gatau cek sendiri asu\
    \n\n•CMD: `.stress`\
    \n•Penjelasan: Gatau cek sendiri asu\
    \n\n•CMD: `.gajelas`\
    \n•Penjelasan: Nyindir orang Goblok\
    \n\n•CMD: `.kismin`\
    \n•Penjelasan: Nyindir orang Goblok\
    \n\n•CMD: `.smph`\
    \n•Penjelasan: Nyindir orang Goblok\
    \n\n•CMD: `.nyg`\
    \n•Penjelasan: bacotin org nyenggol\
    \n\n•CMD: `.lah`\
    \n•Penjelasan: bacotin org kalah\
    \n\n•CMD: `.cwe`\
    \n•Penjelasan: bacotin cewe ghosting\
    \n•CMD: `.gs`\
    \n•Penjelasan: bacotin orang autis\
    \n•CMD: `.jele`\
    \n•Penjelasan: bacotin orang Buriq\
    \n•CMD: `.cih`\
    \n•Penjelasan: bacotin orang dongo\
    \n•CMD: `.tw`\
    \n•Penjelasan: bacotin orang hinaaaa cuiiihhhh."
})
